library(rpart,rpart.plot)
library(rattle)
library(rpart.plot)
library(RColorBrewer)
plot(modeltree)
rf <- rpart(as.factor(X.1) ~ ., data = train.df, method = "class", cp = 0.01 , minsplit = 10)
prf<-prune(rf,cp=rf$cptable[which.min(rf$cptable[,"xerror"]),"CP"])
length(prf$frame$var[prf$frame$var=="<leaf>"])
prp(prf, extra=106,cex =0.6,split.font=1,varlen=-5)

pred <- predict(prf , valid.df , type = "class")
#print(pred)
#print(valid.df$X.1)
#table(as.factor(pred))
#table(valid.df$X.1)
#print(as.factor(valid.df$X.1))
confusionMatrix(as.factor(pred),as.factor(valid.df$X.1))
confusionMatrix( predict(prf , train.df,  type = "class"),as.factor(train.df$X.1) )
summary(prf)
